name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

  # Additional packages you requested
  geolocator: ^9.0.2
  weather: ^3.0.0
  intl: ^0.18.1
  permission_handler: ^10.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
